services:
  create-astral:
    image: ghcr.io/kellegram/create-astral:main
    environment:
        EULA: "FALSE"
        RCON_PASSWORD: "hunter2"
    ports:
      - 25565:25565
    networks: 
      - shared
    volumes:
      - ./ops.json:/data/ops.json:z
      - ./banned-players.json:/data/banned-players.json:z
      - ./banned-ips.json:/data/banned-ips.json:z
      - ./server.properties:/init/server.properties:z
      - astral-world:/data/world:z
      - astral-backup:/data/backup:z

  rcon-cli:
    image: itzg/rcon-cli
    environment:
      RCON_HOST: create-astral
      RCON_PORT: 25575
      RCON_PASSWORD: "hunter2"
    depends_on:
      - create-astral
    networks:
      - shared
volumes:
  astral-world:
  astral-backup:

networks:
  default:
    enable_ipv6: true
  shared:
    driver: bridge
