services:
  create-astral:
    image: ghcr.io/kellegram/create-astral:main
    environment:
      EULA: "FALSE"
      RCON_PASSWORD: "hunter2"
    ports:
      - 25565:25565
    volumes:
      - ./ops.json:/data/ops.json:z
      - ./banned-players.json:/data/banned-players.json:z
      - ./banned-ips.json:/data/banned-ips.json:z
      - ./server.properties:/init/server.properties:z
      - ./rcon.yaml:/etc/rcon.yaml:z
      - astral-world:/data/world:z
      - astral-backup:/data/backup:z

  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: create-astral
      # needs to match the RCON_PASSWORD configured for the container
      RWA_RCON_PASSWORD: "hunter2"
    ports:
      - "4326:4326"
      - "4327:4327"

volumes:
  astral-world:
  astral-backup:

networks:
  default:
    enable_ipv6: true
