#!/bin/sh
if [ -n "$RCON_PASSWORD" ]; then
	rcon-cli --host "localhost:25575" --password "$RCON_PASSWORD" --config "/etc/rcon-cli.yaml" "$@"
else
	rcon-cli --host "localhost:25575" --config "/etc/rcon-cli.yaml" "$@"
fi
